image: bibiota/irunning-server-api:latest

stages:
  - build
  - test

composer:
  stage: build
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - php artisan key:generate
      - php artisan octane:install --server=swoole
  artifacts:
    paths:
      - vendor/
      - .env
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - /root/.composer/vendor/bin/phpunit --coverage-text --colors=never

codestyle:
  stage: test
  dependencies: []
  script:
    - /root/.composer/vendor/bin/phpcs --standard=PSR2 --extensions=php ./app ./tests
